# Numpy

In [2]:
import numpy as np

### Creating Arrays with Zeros, Ones, or Constants
You can create arrays filled with zeros, ones, or any constant using np.zeros(), np.ones(), and np.full():

In [6]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
constant_array = np.full(10, 3)
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### Converting Lists to Arrays
To convert a Python list into a Numpy array, you can use np.array()

In [11]:
my_list = [2, 3, 4]
numpy_array = np.array(my_list)
numpy_array

array([2, 3, 4])

### Generating Ranges of Numbers
Numpy provides functions for generating arrays of sequential numbers. 

In [12]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
range_array = np.arange(4, 10)
range_array

array([4, 5, 6, 7, 8, 9])

### Creating Arrays with Linear Spacing
np.linspace() creates arrays with evenly spaced numbers within a specified range

In [41]:
# Creates 11 numbers from 0 to 1
linspace_array = np.linspace(0, 1, 11)  
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional Arrays
Numpy can handle multi-dimensional arrays, often referred to as matrices. Here are some examples:

In [3]:
zero_matrix = np.zeros((5, 2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
ones_matrix = np.ones((5, 2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

## Indexing and Slicing Arrays
Like Python lists, you can access elements in Numpy arrays using indexing and slicing. For two-dimensional arrays:

In [8]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0] # Gets the first row
arr

array([[2, 3, 4],
       [4, 5, 6]])

In [9]:
first_row

array([2, 3, 4])

In [10]:
first_col = arr[:, 0]
first_col # Gets the first column

array([2, 4])

## Generating Random Arrays
Numpy can create arrays filled with random numbers. To ensure reproducibility, you can set a seed using np.random.seed():

In [53]:
# Set the seed so that the random number generated remains 
# the same no matter what
np.random.seed(2) 

# Generates random numbers between 0 and 1
# random_arr = np.random.rand(5, 2) 

# Generates random numbers between 0 and 100: in this case, 
# each number generated(which remains the same everytime we run)
# is multiplied by 100
random_arr = 100 * np.random.rand(5, 2) 
random_arr

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

For random numbers from a normal distribution or integers within a range:

In [20]:
normal_distribution = np.random.randn(5, 2)
normal_distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [54]:
# the code below is from 0 - 100 with 5 rows and 2 columns
random_integers = np.random.randint(low=0, high=100, size=(5,2))
random_integers

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

## Array Operations
Numpy excels in performing mathematical operations on arrays efficiently.

### Element-wise Operations
You can perform operations on entire arrays element by element:

In [23]:
arr = arr + 1   # Adds 1 to each element
arr

array([[3, 4, 5],
       [5, 6, 7]])

In [25]:
arr = arr * 2   # Multiplies each element by 2
arr
# Similar operations for division and exponentiation

array([[12, 16, 20],
       [20, 24, 28]])

In [56]:
10 + (arr * 2) # we can chain multiple calculation for a numpy array

array([12, 14, 16, 18])

In [57]:
(10 + (arr * 2)) ** 2

array([144, 196, 256, 324])

In [58]:
(10 + (arr * 2)) ** 2 / 100

array([1.44, 1.96, 2.56, 3.24])

## Element-wise Operations with Two Arrays
You can also perform operations between two arrays of the same shape:

In [26]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2  # Element-wise addition
result

array([4., 4., 4., 4.])

In [27]:
result = arr1 / arr2  # Element-wise division
result

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

## Comparison Operations
You can perform element-wise comparisons and create boolean arrays:

In [28]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [29]:
greater_than_2 = arr > 2  # Produces [False, False, True, True]
greater_than_2

array([False, False,  True,  True])

## Selecting Elements Based on Conditions
You can create subarrays based on certain conditions:

In [30]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1
selected_elements

array([2, 3, 4])

In [31]:
min_value = arr.min()    # Minimum value
min_value

1

In [32]:
max_value = arr.max()    # Maximum value
max_value

4

In [33]:
sum_value = arr.sum()    # Sum of all elements
sum_value

10

In [35]:
mean_value = arr.mean()  # Mean (average) value
mean_value

2.5

In [36]:
std_deviation = arr.std()  # Standard deviation
std_deviation

1.118033988749895

In conclusion, Numpy is an essential library for anyone working with numerical data in Python. It simplifies array creation, manipulation, and mathematical operations, making it a powerful tool for scientific computing and data analysis. With the basics covered in this article, you're well on your way to harnessing Numpy's capabilities.