# Linear Algebra Refresher


- Vector operations
- Multiplication
    - Vector-vector multiplication
    - Matrix-vector multiplication
    - Matrix-matrix multiplication
- Identity matrix
- Inverse

In [3]:
import numpy as np

In [66]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

## Vector Operations

In [47]:
# addition
u + v

array([3, 4, 5, 8])

In [48]:
# subtraction
u - v

array([1, 4, 5, 4])

In [49]:
# scalar multiplication
2 * v

array([2, 0, 0, 4])

## Multiplication


### Vector-Vector multiplication

$$\sum\limits_{\substack{i=1 \\ 5}}$$

$$\overset{5}{\sum}$$

The subscripted expression: $$A_{ui}$$

The superscripted expression: $$A^{ui}$$

The expression with an equal sign in the superscript: $$A^{=ui}$$

$$\sum_{i=1}^n a_i = b$$



$$\overset{n}{\sum}\limits_{\substack{i=1}}u_{i} v_{i}$$

The above was written - **\overset{n}{\sum}\limits_{\substack{i=1}}u_{i} v_{i}** in between 2 **$$** sign. 

The expression is for a vector-vector(dot product) calculation. it means that we have a sum - $$\sum\$$

that goes over all elements of our vectors which goes from **1 till n** where **n** is the dimension of the vector then we multiply each element of u with each element of v


In [50]:
# u.shape # this gives us the shape
u.shape[0] # this gives us the number

4

In [51]:
# v.shape # this gives us the shape
u.shape[0] # this gives us the number

4

In linear algebra, the transpose of a vector refers to an operation that converts a column vector into a row vector or vice versa. Transposition essentially flips the vector along its axis, changing its orientation. dot product is represented as:

$$v^{T}u = \overset{n}{\sum}\limits_{\substack{i=1}}u_{i} v_{i}$$

The function below is how we translate the formula above in python

In [52]:
def vector_vector_multiplication(u, v):
    # step 1:
    # make sure that both vectors are the same size. 
    # it is done by checking the shape of the vectors
    assert u.shape[0] == v.shape[0]
    
    # step 2:
    # get the number of element we have
    n = u.shape[0]
    
    # we need the result variable which contains our dot product
    result = 0.0
    
    # step 3:
    # we go over all the element in a loop
    for i in range(n):
        # then we do the product between each element
        result = result + u[i] * v[i]
        
    # finally, we return the result
    return result

In [53]:
vector_vector_multiplication(u,v)

14.0

In [54]:
# the easier way to do the above calculation is through numpy
u.dot(v)

14

## Matrix-Vector Multiplication

In this type of multiplication for eaxample, we have a matrix U that we want to multiply by a vector v:

$$U_v$$

Say matrix U is a 3 x 4 matrix i.e, 3 rows and 4 columns and a single column vector v, we take each row of U and multiply by the vector v. we can represent it as:

$$u_0^Tu$$


$$u_1^Tu$$


$$u_2^Tu$$

Where 0, 1, and 2 attached to u are represents the rows of matrix u and T means transpose (where we convert from row to column or vice versa) each row of the matrix u to a column in order to be able to multiply it by vector v (which is a single column).

**N/B:** the number of numbers that are on a single row of the u matrix must have the same number of numbers in the vector v.

In the next 2 cells is the implementation of this multiplication both in python and numpy

In [69]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [56]:
# U.shape # returns number of rows and columns
# U.shape[1] helps us get the shape of the columns
# U.shape[0] helps us get the shape of the rows
U.shape[1] 

4

In [67]:
def matrix_vector_multiplication(U, v):
    # step 1:
    # make sure that both vectors are the same size. 
    # it is done by checking the shape of the vectors.
    # this time, checking the shape of the column for u against the 
    # column for v
    
    assert U.shape[1] == v.shape[0]
    
    # step 2:
    # get the number of rows we have in U
    
    num_rows = U.shape[0]
    
    # we need the result variable which we will initialize with zeros
    result = np.zeros(num_rows)
    
    # step 3:
    # we go over all the element in a loop
    for i in range(num_rows):
        # then we need to access each row of U and calculate the dot
        # product with the vector_vector_multiplication between each
        # row of U and vector v. remember we already have a function
        # calculates the vector_vector_multiplication and write the
        # result as each element of the result
        
        result[i] = vector_vector_multiplication(U[i], v)
        
    # finally, we return the result
    return result

In [68]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [70]:
U.dot(v)

array([14,  5,  5])

## Matrix-Matrix Multiplication

Our example for this algebra, we have
- a 3 x 4 matrix U and
- a 4 x 3 matrix V

the matrix V is broken down into several columns:

$$V_0$$

$$V_1$$

$$V_2$$

We will then get the entire matrix U. In this instance, the columns of V are transposed into rows. We have matrix U multiplied by each column of vector V (which is each column in V)

$$UV_0$$

$$UV_1$$

$$UV_2$$


In [62]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [1, 2, 1],
    [2, 1, 0]
])

In [63]:
V.shape[0]

4

In [71]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == v.shape[0]
    
    # no of rows will come from U
    num_rows = U.shape[0]
    
    # no of columns will come from V
    num_cols = V.shape[1]
    
    # we create matrix with result
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
        
    return result
    

In [72]:
matrix_matrix_multiplication(U, V)

array([[19. , 20. , 13. ],
       [ 6. ,  6. ,  5. ],
       [ 7. ,  8.5,  9. ]])

In [73]:
U.dot(V)

array([[19. , 20. , 13. ],
       [ 6. ,  6. ,  5. ],
       [ 7. ,  8.5,  9. ]])

## Identity Matrix

It is identified as capital I. it is a square matrix where on the diagonals, we have ones then zeros every other place. When we take any matrix e.g, U, and we multiply it by I, we get U back (even if we put I before U, we'll still get U back). In numpy, we use **np.eye** to create identity matrix

In [74]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
I = np.eye(3)

In [79]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [1. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [80]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [1. , 2. , 1. ],
       [2. , 1. , 0. ]])

The identity (I) matrix is useful for explaining what a matrix inverse is. Say we have matrix A, the inverse of A will be $$A^{-1}
$$

such that when we multiply it by A, we get I. We can use numpy to compute this.

In [85]:
Vs = V[[0, 1, 2]] # taking the first 3 rows (which is counted 0,1,2)
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [1. , 2. , 1. ]])

In [87]:
Vs_inv = np.linalg.inv(Vs) # compute the inverse of Vs
Vs_inv

array([[ 1.00000000e+00, -2.00000000e+00, -1.11022302e-16],
       [-6.66666667e-01,  6.66666667e-01,  6.66666667e-01],
       [ 3.33333333e-01,  6.66666667e-01, -3.33333333e-01]])

In [88]:
Vs_inv.dot(Vs) # we get an identity matrix here
# this will be important in regression

array([[ 1.00000000e+00, -2.22044605e-16, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])