# Housing Data Set

For this homework, we'll use the California Housing Prices dataset.

In [2]:
import numpy as np
import pandas as pd

In [129]:
pd.__version__

'2.0.3'

## Question 1

Read the data with pandas

In [121]:
df = pd.read_csv('housing_data_set.csv')

In [122]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [5]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [6]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND

## Question 2

How many columns are in the dataset?

In [8]:
# num_columns = df.shape[1] # df.shape[0] will give num of rows
# print(f"Number of columns in the DataFrame: {num_columns}")

# or

num_of_columns = len(df.columns)
num_of_columns

10

In [13]:
# side note for rows

# num_columns = df.shape[0] # df.shape[0] will give num of rows
# print(f"Number of columns in the DataFrame: {num_columns}")

# or

# num_of_rows = len(df)
# num_of_rows

## Question 3

Which columns in the dataset have missing values?

**Answer:** total_bedrooms

In [123]:
# df.isnull().sum() 
# or 
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4

How many unique values does the ocean_proximity column have?

**Answer:** 5

In [127]:
# df.nunique() # for the entire table

# or

# df.ocean_proximity.value_counts() # list all the unique values for ocean proximity

# df.ocean_proximity.nunique() # total unique values

# or

df['ocean_proximity'].nunique() # total unique values

5

## Question 5

What's the average value of the median_house_value for the houses located near the bay?

In [133]:
# group median_house_value by ocean_proximity

# df.groupby("ocean_proximity").median_house_value.mean()
# or
# df.groupby("ocean_proximity")['median_house_value'].mean()

# df.groupby("ocean_proximity")['median_house_value'].agg(['mean']) # for different ocean proximity
 
# data.groupby('ocean_proximity')['median_house_value'].agg(['min', 'mean', 'max'])

# mean for those near the bay
df[df.ocean_proximity == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

## Question 6

1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

Has it changed?

Hint: take into account only 3 digits after the decimal point.

- Yes
- No



In [38]:
# 1

# df.total_bedrooms.mean()

# or

mean_value = df['total_bedrooms'].mean()
mean_value

537.8705525375617

In [39]:
# 2

df['total_bedrooms'].fillna(mean_value, inplace=True)

In [40]:
# 3

df.total_bedrooms.mean()

537.8705525375617

## Question 7

1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

**Note:** You just implemented linear regression. We'll talk about it in the next lesson.

-1.4812
0.001
5.6992
23.1233

In [106]:
# 1: filtering

island_data = df[
    df['ocean_proximity'] == "ISLAND"
]

island_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [107]:
# 2

selected_cols = island_data[['housing_median_age', 'total_rooms', 'total_bedrooms']]
selected_cols

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [108]:
# 3

# X = selected_cols.to_dict(orient='records') 
# or
# with the method below, you don't have to convert to a numpy array
X = selected_cols.values 
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [93]:
# # 4a - with the preceeding method, this cell/step is no onger necessary

# # convert the preceeding result to a numpy array
# # arr = np.array(selected_cols)
# # arr

# X = np.array(selected_cols)
# X

In [109]:
# 4b

# we then need to transpose X (X_transpose)

X_transpose = X.T
X_transpose

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [112]:
# 4c

# finally, we compute the matrix-matrix multiplication

result = np.dot(X_transpose, X)
# or
# XTX = X_transpose @ X
# or
# XTX = X_transpose.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [113]:
# 5

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [77]:
# 6

y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [114]:
# 7a

# product_of_XTX_inv = XTX_inv @ X_transpose
# or
product_of_XTX_inv = np.dot(XTX_inv, X_transpose)

product_of_XTX_inv

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [117]:
# 7b

# multiplying our previous result by y
w = product_of_XTX_inv @ y
w

array([23.12330961, -1.48124183,  5.69922946])

In [118]:
# 8

w[-1]

5.6992294550655656